### ISSUE TITLE
DLC versions

### ISSUE THREAD

**Issue by PHF42** [blawar/titledb#11]
First of all, many thanks for this great project!

The file `titles.US.en.json` has been recently removed. Although [the commit message](https://github.com/blawar/titledb/commit/c64b280d8ade102db99106353cd71bef7cf12ed7) suggests to switch to another file, I cannot find any other way to accurately check the latest version of DLCs:

- `versions.json` does not contain DLCs.
- `cnmts.json` contains DLCs but versions are outdated (example: `0100E95004039001` has v131072 while the latest is v196608).
- `US.en.json` contains DLCs but versions are always `null`.

Do I miss something? Any help would be really appreciated!

Thanks!

**Comment by blawar** [comment]
I just added versions.txt for you, this has the DLC versions in it.

**Comment by blawar** [comment]
you should use nut to generate the json file you are accustomed to.  just run nut.py -s on a cron job, every 2 days it will auto download the latest language jsons then rebuild titledb/titles.json which is the same file as titles.US.en.json.

alternatively, you could clone the titledb repo into nut, do git pulls daily and then run "nut.py --import-region US --language en" to regenerate the titles.json.

titles.json flattens all of the language jsons into a single json.  if you read US.en.json, you will only get US titles.

**Comment by PHF42** [comment]
This is exactly what I needed, thanks a lot!

I use your data in custom bash & jq scripts, so it was super easy for me to adapt to the new format :wink:.

Will this new file be regularly updated like the other ones in the future?

**Comment by blawar** [comment]
> This is exactly what I needed, thanks a lot!
> 
> I use your data in custom bash & jq scripts, so it was super easy for me to adapt to the new format 😉.
> 
> Will this new file be regularly updated like the other ones in the future?

That file is updated daily.  Cronjob didn't run last night.
