### ISSUE TITLE
Fields key and version always null

### ISSUE THREAD

**Issue by DblK** [blawar/titledb#13]
Hi,
I think between the 12/09 and 12/16 the content of the files changed.
Now the field `key` and `version` are always `null`.

For example :
- `010000001260E000` has `version` `0` and `key` `FEEB99E9E97F5E7F1F2D2821E503CD45`

Will it be possible to fix that?

**Comment by blawar** [comment]
base games almost always have a version of zero, with the exception of snake pass and sparse storage games.

keys should not be set.

**Comment by DblK** [comment]
Can you elaborate why `keys should not be set`?
I used the titledb to compare with the ticket id to see if everything match or not. Is there a better way to prevent `NCA fails` in `tinfoil`?

If you decide to change the data and remove it, why still keeping the fields that are always `null`.
