### ISSUE TITLE
cnmts.json hasn't been updated in 10 days

### ISSUE THREAD

**Issue by HamletDuFromage** [blawar/titledb#15]
Is there any reason for that? The other files seem to be updated daily, is that one not going to get updates anymore?

Thank you for the database though!

**Comment by borntohonk** [comment]
While it's probably a bit of gossip and that it'd seem unlikely that it'd be related, the last tech member of "hbg" left the scene the 2nd and shut down their groups vps. Apparently that has affected some parts of an ecosystem which assumed things would last forever.

**Comment by blawar** [comment]
json was corrupted on the server due to running out of disk space, and jammed up the cron jobs
