### ISSUE TITLE
DLC versions null

### ISSUE THREAD

**Issue by mspykerez** [blawar/titledb#16]
Did something changed regarding DLC versions?

I often run https://github.com/giwty/switch-library-manager that uses this database to check for missing updates and I notice that it is not detecting DLC-updates anymore... i tested by deleting a DLC update file that I'm sure it was detecting as missing just a few months back but now it isn't.
It seems to be detecting missing updates for base games just fine thou.

A quick look on my hand shows that US.en.json is reporting DLC versions as null, not sure if that is the file that Switch Library Manager is grabbing, if it is I guess that's the culprit.

**Comment by blawar** [comment]
I would speak to the app author.  DLC versions are still reported in this database.  The latest commit is here: https://github.com/blawar/titledb/commit/c3c12aac5823a32d491d1d62b9edf69c9cb5e6ab

search for 01007090154b7001 which is a DLC

**Comment by mspykerez** [comment]
Switch Library Manager hasn't been updated in a year and was detecting missing DLC updates just fine up until some months back so I thought something must have changed to the files that it grabs from here when you start the app.

cnmts.json seems to be the only file where DLC-updates are properly listed, perhaps Switch Library Manager is grabbing other file instead.

**Comment by mspykerez** [comment]
Just wanted to add that Nintendo recently changed their site, it's visually different, things are reported differently and at the same time it's way slower.

This to say that the changes on nintendo's side could have impacted how they are reporting the data that titledb is grabbing in such a way that now titledb is generating or structuring it differently than before.

Unfortunately I don't know how to fix the issue with Switch Library Manager, it seems just a matter of pointing it to grab the right file from titledb at startup but I have no clue how to do that.
I opened a ticket there, hopefully the author comes back from MIA and fixes it, else I don't know what to do...

**Comment by blawar** [comment]
No, the dlc versions are also in versions.txt: https://github.com/blawar/titledb/commit/c00f97d3ddc8be381c3c1d4895e6dca5cd4b8f2c

Search for 0100876015D75001.

**Comment by mspykerez** [comment]
The DLC you mentioned indeed appears to show that it has an update (65536) in versions.txt however that seems to not be the case for all DLCs, like 'CHILDREN OF MORTA: PAWS AND CLAWS' DLC with the ID 01002DE00C251001 versions.txt shows the DLC but it does not show that it has an update available, I believe that even tinfoil.io shows there is an update for it, so something must be wrong, I dunno...

**Comment by blawar** [comment]
ok, so you report is that versions.txt is wrong, I can fix that.

**Comment by mspykerez** [comment]
Sorry to bother but has this been fixed yet?
At least for me SLM seems to still be giving incomplete reports.

**Comment by PHF42** [comment]
Hi! Just to confirm I'm also facing this issue. Most DLCs have their version empty in `versions.txt`.
Here is a random example: `01006A800016F004`.

I hope it's not too difficult to fix! 🤞

Thanks!

**Comment by 16BitWonder** [comment]
To add to this, it was noticed in [NX-Update-Checker#28](https://github.com/16BitWonder/NX-Update-Checker/issues/28) that versions.json currently does not include any DLC versions.
Figured to mention this in the event that wasn't intentional.

**Comment by blawar** [comment]
> To add to this, it was noticed in [NX-Update-Checker#28](https://github.com/16BitWonder/NX-Update-Checker/issues/28) that versions.json currently does not include any DLC versions.
> Figured to mention this in the event that wasn't intentional.

Versions.json is based on hacversionlist which does not report dlc.  Do you have a dlc titleid that is reporting an incorrect version?

**Comment by mspykerez** [comment]
I think that [Switch Library Manager](https://github.com/giwty/switch-library-manager) grabs versions.json from titledb as is but it also automatically generates another file with different information called titles.json which I believe is where it checks for missing DLC updates.
The problem is that somewhere in the past few months I notice that SLM  stopped reporting newer DLC versions and since SLM hasn't been updated in a while I can only assume that something has changed at titledb's end that makes SLM generate the file with missing information (probably because titledb's is also missing that information somewhere along the way).

**Comment by 16BitWonder** [comment]
> Versions.json is based on hacversionlist which does not report dlc. Do you have a dlc titleid that is reporting an incorrect version?

I do not have incorrect DLC versions to my knowledge, I grab DLC version info from your versions.txt/cnmts.json.
My bad about versions.json, there's no issue with that then.

**Comment by blawar** [comment]
I did a hard refresh of all dlc versions for you @mspykerez @16BitWonder https://github.com/blawar/titledb/commit/b48da4b2dc4d518d6e53c9f78a53d7951ab9682e

**Comment by mspykerez** [comment]
@blawar 

Thx for the effort man but it did not fix the SLM problem of not reporting missing DLC versions.
I was looking at slm.log and found that it appears to get the data from this 2 addresses:
https://tinfoil.media/repo/db/versions.json and https://tinfoil.media/repo/db/titles.json

If I'm not mistaken that addresses are tied here to titledb so unless it takes some time for the 'hard refresh' to kick in there, some DLC updates still appear as 'null' at titles.json hence I believe this is the cause of the problem.

**Comment by mspykerez** [comment]
Good news!
I've checked again today and it's working! Something has definitely kicked in that now makes https://tinfoil.media/repo/db/titles.json list the missing DLC versions that were previously marked as 'null' and consequently SLM is able to detect them up. Although I cannot confirm if that is the case with all DLCs it seems to have fixed the few ones I knew for certain that at some point had a DLC update that wasn't being reported.
Some fields at https://tinfoil.media/repo/db/titles.json still appear as 'null' but I think that's related to not so important information that do not interfere with update versions.

@blawar  Question now is if this is a permanent fix that you did or you'd have to manually do an 'hard refresh' or whatever every time in order to make sure everything is listed properly?

**Comment by blawar** [comment]
> Good news! I've checked again today and it's working! Something has definitely kicked in that now makes https://tinfoil.media/repo/db/titles.json list the missing DLC versions that were previously marked as 'null' and consequently SLM is able to detect them up. Although I cannot confirm if that is the case with all DLCs it seems to have fixed the few ones I knew for certain that at some point had a DLC update that wasn't being reported. Some fields at https://tinfoil.media/repo/db/titles.json still appear as 'null' but I think that's related to not so important information that do not interfere with update versions.
> 
> @blawar Question now is if this is a permanent fix that you did or you'd have to manually do an 'hard refresh' or whatever every time in order to make sure everything is listed properly?

So, the problem your app has is that it is using an unsupported file.  It should not rely on that file.  It appears the app developer was being lazy when titles.US.en.json was deprecated.  Rather than adjust the app to use other files, they hot linked a temporary file on the website.

your app will continue to have problems as long as it’s using that file.  Honestly I should have blacklisted that file along time ago, people have had plenty of time to migrate away from it.

**Comment by mspykerez** [comment]
> your app will continue to have problems as long as it’s using that file. Honestly I should have blacklisted that file along time ago, people have had plenty of time to migrate away from it.

https://github.com/giwty/switch-library-manager hasn't been updated in a while and the dev seems MIA but maybe he come back I dunno.
I've looked for forks and didn't find any active one which is quite a shame since it's the only app I know that can detect missing game updates and dlc directly from your PC by scanning all the files at once in a folder I point it to recursively without needing to use the Switch at all. Unfortunately I'm no coder hence don't know how to fork and fix the issue at switch-library-manager end.

I also have a semi-related question regarding titledb missing some legit physical games which have a different ID from the digital versions I think, like this ones:

Azure Striker GUNVOLT: STRIKER PACK - 01003c100655a000
Owlboy - 0100e570094e8000
Slain - 0100bb100af4c000
SteamWorld Dig 2 - 0100562008698000
Wonder Boy: The Dragon's Trap - 01001b7008ee8000

They don't appear on tinfoil.io but they do appear at nswdb.com so I wonder if there is a way for titledb to pick them up as well ?

**Comment by blawar** [comment]
> > your app will continue to have problems as long as it’s using that file. Honestly I should have blacklisted that file along time ago, people have had plenty of time to migrate away from it.
> 
> https://github.com/giwty/switch-library-manager hasn't been updated in a while and the dev seems MIA but maybe he come back I dunno. I've looked for forks and didn't find any active one which is quite a shame since it's the only app I know that can detect missing game updates and dlc directly from your PC by scanning all the files at once in a folder I point it to recursively without needing to use the Switch at all. Unfortunately I'm no coder hence don't know how to fork and fix the issue at switch-library-manager end.
> 
> I also have a semi-related question regarding titledb missing some legit physical games which have a different ID from the digital versions I think, like this ones:
> 
> Azure Striker GUNVOLT: STRIKER PACK - 01003c100655a000 Owlboy - 0100e570094e8000 Slain - 0100bb100af4c000 SteamWorld Dig 2 - [0100562008698000](tel:0100562008698000) Wonder Boy: The Dragon's Trap - 01001b7008ee8000
> 
> They don't appear on tinfoil.io but they do appear at nswdb.com so I wonder if there is a way for titledb to pick them up as well ?

Titledb is based on CDN data, the CDN does not provide any data for xci only games.  So if there is a titleid that is xci only, we will not have any metadata on it.  And there is nothing we can do unless we maintained our own custom metadata for xci only title id’s (which no one wants to do, because frankly few people care about XCI’s).

**Comment by mspykerez** [comment]
> Titledb is based on CDN data, the CDN does not provide any data for xci only games. So if there is a titleid that is xci only, we will not have any metadata on it. And there is nothing we can do unless we maintained our own custom metadata for xci only title id’s (which no one wants to do, because frankly few people care about XCI’s).

OK np.

Now to wrap this up will you keep https://tinfoil.media/repo/db/titles.json active? if so what kind of problems may I encounter in the future while SLM keeps using it?

If only I knew how to make SLM stop using the deprecated file and instead use/generate the data based on the new standard...
If you blacklist it I'm afraid it will totally break SLM and I don't know of any working alternatives that do a similar job.

**Comment by blawar** [comment]
I have no plans to blacklist it currently.  The file is easy to generate (nut generates it) if someone else wanted to host it.  I’ll take a look at the app whenever I have time to see if it’s easy to submit a PR.

**Comment by mspykerez** [comment]
> I have no plans to blacklist it currently. The file is easy to generate (nut generates it) if someone else wanted to host it. I’ll take a look at the app whenever I have time to see if it’s easy to submit a PR.

My gratitude!

Also, not wanting to drag it much longer I just notice that some of the physical games I mentioned above have the titleID listed at titledb but for some reason aren't listed at tinfoil.io with that titleID.
As far I can tell:

Azure Striker GUNVOLT: STRIKER PACK - 01003c100655a000 > listed at versions.txt + versions.json + cnmts.json + ncas.json
Owlboy - 0100e570094e8000 > listed at versions.txt + versions.json + cnmts.json + ncas.json

Slain - 0100bb100af4c000 > only listed at versions.txt
SteamWorld Dig 2 - 0100562008698000 > only listed at versions.txt
Wonder Boy: The Dragon's Trap - 01001b7008ee8000 > only listed at versions.txt

Not sure if that is intended and goes with what you said before or it's a bug on tinfoil.io end.

**Comment by mspykerez** [comment]
One more thing.. are the region/language files such as US.en.json supposed to give back a ‘null’ value on the DLC versions even when an update for them exists? Looking at it it’s listing the DLCs but the versions are always ‘null’ as far I can see, maybe an ‘hard refresh’ is also required to fix this?

Anyway thank you very much for your time 👍

**Comment by jonasmare** [comment]
@blawar 

I haven’t used Tinfoil homebrew on the Switch for a long time but I hear that now it has lifted the restrictions that were limited to SX OS users so I’m more interested on it.

Reading this thread I was wondering if it is possible for Tinfoil to report missing game updates and DLC versions without using any ‘shops’ whatsoever but rather connect to this repo and grab the data to look for what is outdated? And for those who wish to remain offline possibly manually download the necessary files from here (if they are not already bundle with Tinfoil) and put into the right place on the Switch where Tinfoil can read them (off course this way Tinfoil will only be able to correctly report up to the date we get the files).

I also would like to know if NUT can be used to ‘scan’ a folder in the PC for new games, updates, dlc, etc and selectively show newer updates and dlc files it finds for the games we already have installed on the Switch and at the same time report if those files are indeed the latest version according to titledb but also list updates and dlc for new games that NUT finds on the PC that aren't installed on the Switch (it needs to look for matches between the base game files and updates/dlc files that we have stored), preferably it will do this not only by looking at the titleID in the files names but also scan inside the files themselves to look for the ID in the absence of not finding any ID on the naming like Switch Library Manager does.

Not sure if any of the above can already be done, I'd appreciate a clarification if you could.


> (which no one wants to do, because frankly few people care about XCI’s).

On this I may disagree, I think a lot of people would like the ability to have XCI loading, especially for loading games from an external drive but I hear that it is not something that can be done solely by an homebrew app and needs to be implemented at CFW level plus people say it will not gonna happen because it requires the use of Nintendo's code or whatever.
That is all word of mouth though and if anyone could do it I think it would be you and it should be a killer feature to have for Tinfoil.

**Comment by jonasmare** [comment]
@mspykerez 
I’ve noticed some problems with tinfoil.io website too, generally the site is a bit slow but nothing that we can’t live with.

What I see is that the filters that we select do not apply to anything shown on the DLC tab, they only appear to filter stuff on the TITLES tab. The other thing is that some fields on some game info pages appear blank such as ‘languages’, ‘version’, ‘rating’

> I believe that so many things shown in these filters atm are just duplicate stuff written on a different language that most people don’t even understand.

As an example of this issue when you go to the categories tab it’s obvious that it’s showing duplicate categories that are written on different languages like ‘acción’ which is the same as ‘action’.

I also have a few suggestions of my own for tinfoil.io site:

- In addition to the 'blacklist' feature that was suggested @mspykerez Id' very much like to choose between ‘AND’ , ‘OR’ operators when selecting multiple filters;
- Show game genres and embedded trailer on the game info page;
- Connect the Switch to the site and have it detect and show which installed games have a new update or dlc available on the site itself;
- Ability to manually subscribe/follow games on the site and get notifications when a new update or dlc is released for them.

**Comment by mspykerez** [comment]
Seems like https://tinfoil.media/repo/db/titles.json is 'stuck' again... could be an issue on tinfoil.io end because the site itself is not listing some of the latest available updates despite [versions.json](https://github.com/blawar/titledb/blob/master/versions.json) and [versions.txt](https://github.com/blawar/titledb/blob/master/versions.txt) listing them, for this game for example https://tinfoil.io/Title/0100439016FF6000

**Comment by mspykerez** [comment]
After a few weeks, looks like that as of a few hours ago tinfoil is now correctly reporting the updates.

**Comment by blawar** [comment]
> After a few weeks, looks like that as of a few hours ago tinfoil is now correctly reporting the updates.

I had to migrate the server a few weeks ago due to some google issues, and these problems stem from that.  There are many moving pieces to this system, its  actually more complex than most would realize.  I saw your message yesterday, and took steps to fix some of the steps, the likely result of that was the db being served to tinfoil being fixed.  I am still working on some reamining pieces for the tinfoil.io site.

thank you for bringing the issue to my attention.

**Comment by jonasmare** [comment]
@blawar  something seems wrong, tinfoil db has not been updated for a week now.

**Comment by blawar** [comment]
> @blawar something seems wrong, tinfoil db has not been updated for a week now.

Thank you, cron job died.  Its running now, should update tonight. Re-open if the issue persists tomorrow.

**Comment by mspykerez** [comment]
Sometimes titledb gets stuck, 3 days now with no updates..

@blawar is it normal for tinfoil.io to show some games that have yet to be released but are listed on nintendo's site with a future release date like Sonic Frontiers but at the same time neglect other games that are also listed on nintendo's site with a future release date like Bayonetta 3 ?

**Comment by giwty** [comment]
> > Good news! I've checked again today and it's working! Something has definitely kicked in that now makes https://tinfoil.media/repo/db/titles.json list the missing DLC versions that were previously marked as 'null' and consequently SLM is able to detect them up. Although I cannot confirm if that is the case with all DLCs it seems to have fixed the few ones I knew for certain that at some point had a DLC update that wasn't being reported. Some fields at https://tinfoil.media/repo/db/titles.json still appear as 'null' but I think that's related to not so important information that do not interfere with update versions.
> > @blawar Question now is if this is a permanent fix that you did or you'd have to manually do an 'hard refresh' or whatever every time in order to make sure everything is listed properly?
> 
> So, the problem your app has is that it is using an unsupported file. It should not rely on that file. It appears the app developer was being lazy when titles.US.en.json was deprecated. Rather than adjust the app to use other files, they hot linked a temporary file on the website.
> 
> your app will continue to have problems as long as it’s using that file. Honestly I should have blacklisted that file along time ago, people have had plenty of time to migrate away from it.

@blawar - can you please guide me on what file should i use ? will need both the version and titles file.
(btw, has nothing to do with being lazy, genuinely thought im using the a legit file)

**Comment by blawar** [comment]
> Sometimes titledb gets stuck, 3 days now with no updates..
> 
> @blawar is it normal for tinfoil.io to show some games that have yet to be released but are listed on nintendo's site with a future release date like Sonic Frontiers but at the same time neglect other games that are also listed on nintendo's site with a future release date like Bayonetta 3 ?

Tinfoil.io won’t show the games until they have a title id. So while we do get the metadata early, it doesn’t show up until nintendo assigns a title id. This is because tinfoil.io indexes on the title id.

**Comment by blawar** [comment]
> > > Good news! I've checked again today and it's working! Something has definitely kicked in that now makes https://tinfoil.media/repo/db/titles.json list the missing DLC versions that were previously marked as 'null' and consequently SLM is able to detect them up. Although I cannot confirm if that is the case with all DLCs it seems to have fixed the few ones I knew for certain that at some point had a DLC update that wasn't being reported. Some fields at https://tinfoil.media/repo/db/titles.json still appear as 'null' but I think that's related to not so important information that do not interfere with update versions.
> > > @blawar Question now is if this is a permanent fix that you did or you'd have to manually do an 'hard refresh' or whatever every time in order to make sure everything is listed properly?
> > 
> > 
> > So, the problem your app has is that it is using an unsupported file. It should not rely on that file. It appears the app developer was being lazy when titles.US.en.json was deprecated. Rather than adjust the app to use other files, they hot linked a temporary file on the website.
> > your app will continue to have problems as long as it’s using that file. Honestly I should have blacklisted that file along time ago, people have had plenty of time to migrate away from it.
> 
> @blawar - can you please guide me on what file should i use ? will need both the version and titles file. (btw, has nothing to do with being lazy, genuinely thought im using the a legit file)

The files in the GitHub repo.

**Comment by mspykerez** [comment]
@blawar  can you make the NUT show missing updates/dlc of the files it scans on a local computer without to much hassle?

**Comment by blawar** [comment]
> @blawar can you make the NUT show missing updates/dlc of the files it scans on a local computer without to much hassle?

just output a text file?  for missing and out of date dlc and updates?

**Comment by jonasmare** [comment]
> just output a text file? for missing and out of date dlc and updates?

Could work like https://github.com/16BitWonder/NX-Update-Checker difference being that it would scan your computer for compatible files (xci, nsp, etc) instead of just scanning installed titles in the Switch itself and report it on the GUI or output the missing stuff to a log file.

Anyway came here to notify that titledb and consequently tinfoil has not been updated in a week.
Something must have failed in the backend?

**Comment by blawar** [comment]
@jonasmare had a cut fiber line, should update tonight.

**Comment by jonasmare** [comment]
Don't know if it is intended but now titledb is getting updates like crazy but still takes a while to show up on tinfoil.
Not minding that tinfoil takes a while to update, just letting you know that the backend may be doing more work than it is supposed to instead of just updating once a day or so.

**Comment by blawar** [comment]
> Don't know if it is intended but now titledb is getting updates like crazy but still takes a while to show up on tinfoil.
> Not minding that tinfoil takes a while to update, just letting you know that the backend may be doing more work than it is supposed to instead of just updating once a day or so.

The frequency update was intended, however tinfoil is only updated 1-3 days, don’t want clients constantly downloading updates.
