### ISSUE TITLE
Link "Base" id to "Update" id

### ISSUE THREAD

**Issue by johnlescault** [blawar/titledb#19]
Hi, I'm looking for a way to link the base game id to the update id. If we use Zelda Breath of the Wild for example:

using US.en.json: 
`Find that the Base ID is 01007ef00011e000`

using versions.json: 
```
Find that there are the following updates:
    "01007ef00011e000": {
        "393216": "2017-08-14",
        "524288": "2017-11-08",
        "589824": "2017-11-21",
        "655360": "2017-12-08",
        "720896": "2018-01-31",
        "786432": "2019-04-25"
```

Is there a way to somehow cross reference that to bring
```
    "01007ef00011e800": {
        "720896": "2018-10-09"
```

I'm essentially looking for a way to programically get the update id 01007ef00011e800. 

DLCs seem to be included in US.en.json, but updates aren't, so just looking for a work around.

Side questions: When looking in US.en.json, when ID is null does this mean anything? Was it a game not released? I noticed many of them are demos but it does not seem like they all are.

Thanks

**Comment by blawar** [comment]
Update Id's always end in 800.  But if you really wanted a *hard* way to link them, you can do so with cnmt.json's "otherApplicationId":

```
    "0100041018810000": {
        "0": {
            "contentEntries": [
                {
                    "buildId": "80329F07550C8B545139D708AF568729CDB377DA000000000000000000000000",
                    "ncaId": "32b431d24dae7f6d2ae3b3b031dd4af2",
                    "type": 1
                },
                {
                    "ncaId": "b30f3e84c4d26bbaa9ebfcd28d0dbe19",
                    "type": 3
                },
                {
                    "ncaId": "0b819a62634b15d314b89b7d05056125",
                    "type": 5
                }
            ],
            "metaEntries": [],
            "otherApplicationId": "0100041018810800",
            "requiredApplicationVersion": 0,
            "requiredSystemVersion": 940703744,
            "titleId": "0100041018810000",
            "titleType": 128,
            "version": "0"
        }
    },
    ```

**Comment by johnlescault** [comment]
Thanks for the answer! This will work! Also a huge thanks for all your work with this and all the other applications you have developped!

After submitting that question, I experimented making my own "titles.json" file using your instructions:
```
git clone https://github.com/blawar/titledb titledb
git -C titledb pull
nut.py -U --import-region US --language en
```
The file is larger than the US.en.json file and seems to also include the updates, would this file essentially be what I end up creating using the **otherApplicationId** file? All I'm doing right now is taking the ID from US.en.json and making a list (and I'll also add the "otherApplicationId" for updates.
