### ISSUE TITLE
(question) US.en.json vs filtered title.json

### ISSUE THREAD

**Issue by johnlescault** [blawar/titledb#20]
Hi, I'm just trying to figure out the differences between the files. I thought if I used US.en.json mixed with cnmts.json I would get a complete list of US region games, DLC and updates. I think I may have been wrong?

**My question is, what is the difference(s) between title.json (assuming I filter by US) and US.en.json?** My concern is filtering title.json by region excludes updates so I still have to cross reference cnmts.json, along with downloading a bigger file. I understand I could just change the last three numbers to 800, but that feels slightly lazy and if ever anything changes with that I could be missing updates.

Also, some of the games in US.en.json dont have an 'id' set. What does this mean? See sample below:

```
"70010000022989": {
        "bannerUrl": "https://img-eshop.cdn.nintendo.net/i/2f7a847e7fe53370b7327d30bce9bd86c258a9f944e2501d5a4c26284e753389.jpg",
        "category": [
            "Action",
            "Other"
        ],
        "description": "The true sequel to Deadly Premonition is coming to Nintendo Switch.\n\nIn the year 2005, FBI agent York visits Le Carr\u00e9, a small town in New Orleans where he encounters a mysterious serial murder case alongside his \u201cfriend\u201d Zach.\n\nProduced by the original creator team. The story takes place in a small town in New Orleans which was created based on research and interviews.",
        "developer": null,
        "frontBoxArt": null,
        "iconUrl": null,
        "id": null,
        "intro": null,
        "isDemo": false,
        "key": null,
        "languages": [
            "en"
        ],
        "name": "Deadly Premonition 2: A Blessing in Disguise",
        "nsuId": 70010000022989,
        "numberOfPlayers": 1,
        "publisher": "Rising Star Games",
        "rating": 17,
        "ratingContent": [],
        "region": null,
        "releaseDate": 2020,
        "rightsId": null,
        "screenshots": [
            "https://img-eshop.cdn.nintendo.net/i/37442483c053541f41bbb9f04ed25ab591a48c96effb16d00887c9650a986a70.jpg",
            "https://img-eshop.cdn.nintendo.net/i/242540105861cfb8108841d8e36f9482b2da086b6f599f8d6b4d8abc2867e3e6.jpg",
            "https://img-eshop.cdn.nintendo.net/i/6feaba550b1d4cdf6f7f57b4bd1b4e14b629fd46a3823317e7d3572ee566fd5e.jpg",
            "https://img-eshop.cdn.nintendo.net/i/935ea5cb3cd41d4e127c736b4b470d053ea6c77d431c6635e196b5afcbdce2a2.jpg",
            "https://img-eshop.cdn.nintendo.net/i/5fcb761c8035b1d76d8c13c38fecafb65ba05abd1e49c48432d2bf7875b7f296.jpg",
            "https://img-eshop.cdn.nintendo.net/i/de9083b212ff93297caace52b11c8dd229f82e8c9428123a6477fbca2a275f23.jpg"
        ],
        "size": 0,
        "version": null
    },


```

I appologize if these are "newbie" questions. I couldn't find the answers anywhere else.

**Comment by blawar** [comment]
Don’t use US.en.json, only use titles.json.

the difference is in the name, the former is not a complete database, it is region specific data that is used to build titles.json.

just add 800 to the end for the patch id, it’s been 7 years, they aren’t changing it.

**Comment by johnlescault** [comment]
I don't mean to be questioning you if it comes off that way (I totally realize you understand WAY more about these files then I ever will), but would just like to know for my own knowledge. If I'm **only** interested in US titles, would I be missing anything by only using the US.en.json?

**Comment by blawar** [comment]
US.en.json is indexed on the nsuId not the title id (which is probably what you want). titles.json is indexed on the title id (what you want). titles.json will also have additional information such as update information.

**Comment by My1** [comment]
where is the titles.json anyway? the readme says it's in a folder called titledb but this repo doesnt have any subfolders and no titles.json directly either

**Comment by blawar** [comment]
> 

its in titledb folder of a nut installation. not in this repo.
