### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by mariomadproductions** [blawar/titledb#22]
Could you releasing the source code to the scraping tool used for this? It'd be useful for switch game preservation.

**Comment by blawar** [comment]
The tools at one time were all open source, but then many people abused it which lead to very dark times. Now everyone keeps them closed source to prevent further damage to scene.

**Comment by blawar** [comment]
> I see. Alternatively, could the full eshop metadata be included in the repo? I believe that the JSON objects here are processed/a summary of the full data?

That would be massive, and would not be useful to most people. The raw data is at least 50GB of text. Do you have experience working with the raw eshop metadata? If I published it, it would be in a different repo.  I don't even know if github would accept it, its so large.

**Comment by mariomadproductions** [comment]
I have some experience with the metadata for the precious Nintendo consoles, and a little bit with Switch. Is it still 50GB when compressed?

**Comment by blawar** [comment]
> I have some experience with the metadata for the precious Nintendo consoles, and a little bit with Switch. Is it still 50GB when compressed?

No, it compresses well. But I can’t upload it to github compressed and continually update it.

**Comment by mariomadproductions** [comment]
If you do this in the folder:
````
git init
git bundle create repo.bundle --all
```
How big is the bundle file? Maybe it'll be less than 50GB, which suggests to me that the repo may not take up 50GB on gitbub's servers.
