### ISSUE TITLE
Site stuck

### ISSUE THREAD

**Issue by jonasmare** [blawar/titledb#23]
Dont know what is going on but changes (updates) in the files on this repo are not reaching tinfoi.io's website.

**Comment by Devilin-Pixy** [comment]
Same issue, appears to happen regularly for a while now. No Man's Sky is often behind due to titledb no longer regularly updating, but even if it updates, these are not always reflected on tinfoil after.

**Comment by ffhome** [comment]
I hope someone can continue updating titledb, thanks a lot！

**Comment by ffhome** [comment]
> > I hope someone can continue updating titledb, thanks a lot！
> 
> I restarted the cron job, should update soon.

It has been updated, and I am very happy. Thank you for your work!
