### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Clearmist** [blawar/titledb#24]
0100B6801137E000 is a demo. Please set isDemo to true.

**Comment by blawar** [comment]
Nintendo has many errors like this, we previously tracked them.  I will investigate to see if this is possible.

**Comment by Clearmist** [comment]
Ah, you're using an automated task to scrape the metadata. Correcting this one error from N, or tracking similar errors in other entries, would be too much work. Nevermind, and thank you for the work you've already put into this database. 😊

**Comment by blawar** [comment]
Are you using this database with nut? You can manually set the demo
override with a demos.txt file
