### ISSUE TITLE
Files are often updated with incorrect format

### ISSUE THREAD

**Issue by a1ex4** [blawar/titledb#28]
Hi, oftentimes the json files are updated with incorrect format, which means they can't be read (currently it's cnmts.json).

Could you add something to prevent that? Maybe a git pre commit hook to not commit unreadable files? Or a Github Action CI to at least indicate that a commit is unusable and notify in case of an issue ? I could quickly do it if you're willing to add that.

Thanks

**Comment by blawar** [comment]
its fixed, server ran out of disk space
