### ISSUE TITLE
Repository Stopped Updating

### ISSUE THREAD

**Issue by Hornetsaysshaw** [blawar/titledb#30]
The respository hasn't been updated for three days and [this](https://tinfoil.media/repo/db/versions.json) hasn't either. Hopefully this can be fixed. Thank you for maintaing this.

**Comment by Hornetsaysshaw** [comment]
Fixed. Thank you for your work.

**Comment by blawar** [comment]
Thx for your report, I fixed it after reading your issue @Hornetsaysshaw
