### ISSUE TITLE
NSU for released December 2023 DLCs missing titleid

### ISSUE THREAD

**Issue by wasabidon** [blawar/titledb#32]
For example in US.en.json:
70050000038769 (id should be 010046B00DE63005 but it's null)
70050000042314 (id should be 0100380017D3F003 but it's null)

**Comment by blawar** [comment]
DLC are problematic/difficult to get updates to without doing a full scan. Generally the full scan to pick up missing DLC’s is done once a month or so.

this situation usually comes up when a title launches with a set number of dlc, and then new dlc are added later which aren’t picked up as quickly as most would like.

**Comment by wasabidon** [comment]
Got it, now that I understand they will eventually update then it's not an issue.
Thank you for your work! 🙏
