### ISSUE TITLE
Version correlation

### ISSUE THREAD

**Issue by Veleras** [blawar/titledb#34]
I'm trying to find a relationship between the version number of the versions.json file with the x.x.x patch notation

This exists ?
How do you identify which version X of a game is the latest ?

For example in Legend of Zelda breath...

"01007ef00011e000": {
        "393216": "2017-08-14",
        "524288": "2017-11-08",
        "589824": "2017-11-21",
        "655360": "2017-12-08",
        "720896": "2018-01-31",
        "786432": "2019-04-25"
    },

    "524288": "1.3.3",
    "589824": "1.3.4",
    "655360": "1.4.0",
    "720896": "1.5.0",
    "786432": "1.6.0"
    
    This would be the relationship according to the dates on the official website of the game

Thank you so much !!!

**Comment by throwawayay** [comment]
Look at the meta info in the patch file (assuming you have it)

**Comment by Veleras** [comment]
I don't have any files related to the games.
It is only the list of games available with their dlcs and versions, in a format that people understand as they appear on some official pages with the number 1.xx.xx and not as 654464

**Comment by throwawayay** [comment]
Unfortunately they do not
