### ISSUE TITLE
Missing NSUs that should exist in US.en.json

### ISSUE THREAD

**Issue by wasabidon** [blawar/titledb#35]
Recently I checked some titles only exist in KR.ko.json (01000C9015D42000 and 0100F0E01CADC000) but these supposedly also exist in US shop.

Then I checked these titles should be contained in these USA nsus, but they don't exist in US.en.json:

01000C9015D42000: 70010000044362
0100F0E01CADC000: 70010000071305

There could be more but these are the ones I've spotted for now.

**Comment by wasabidon** [comment]
Here are more missing nsu entries in US.en.json that I found (and their expected id and releaseDate values)

nsuId:70010000044362 id:01000C9015D42000 releaseDate:20231109
nsuId:70010000071305 id:0100F0E01CADC000 releaseDate:20231109
nsuId:70010000070081 id:0100CAC01C3EC000 releaseDate:20231109
nsuId:70010000073459 id:010018401D34E000 releaseDate:20231111
nsuId:70010000069038 id:01002F801BEA8000 releaseDate:20231112
nsuId:70010000064674 id:0100B6301ABD6000 releaseDate:20231114
nsuId:70010000061768 id:0100ADB019DDA000 releaseDate:20231114
nsuId:70010000064211 id:010094E01AA20000 releaseDate:20231114
nsuId:70010000073068 id:01009E300F83A000 releaseDate:20231115
nsuId:70010000070346 id:010037A01C53A000 releaseDate:20231117

**Comment by wasabidon** [comment]
I see them now. Thank you for updating!

**Comment by blawar** [comment]
> I see them now. Thank you for updating!

Its still updating, I took the opportunity to refresh the entire database which will take days. You should see a lot more data coming in, in about 2 days.
