### ISSUE TITLE
Titledb needs an update.

### ISSUE THREAD

**Issue by ray1025** [blawar/titledb#36]
The title with the ID 010074F013263004 already has version v131072 available.

**Comment by masagrator** [comment]
Overall there are some weird misses. 

Pokemon Violet and Scarlet have v11 update for some time while it still shows v10.
We Love Katamari has v3 while versions show v2.

**Comment by blawar** [comment]
> Overall there are some weird misses.
> 
> Pokemon Violet and Scarlet have v11 update for some time while it still shows v10. We Love Katamari has v3 while versions show v2.

Likely some gaps when my server was down (and not scanning) due to hardware failure, and I just noticed that I forgot to setup a weekly cron job for doing full scans on the new server (which would have eventually filled those gaps).

Full scan is running now, should not be an issue moving forward.

**Comment by jonasmare** [comment]
looks like the site is updated, seems faster and all, but the github repo here is not, usually it's the other way around

**Comment by blawar** [comment]
> looks like the site is updated, seems faster and all, but the github repo here is not, usually it's the other way around

job is still running, give it another hour.

**Comment by blawar** [comment]
the git repo should be up to date and accuarate now @jonasmare @masagrator 

please re-open if you find any discrepencies.

https://github.com/blawar/titledb/commit/e973ed0f162399dfa587a43b3a253e8afe05a09e

**Comment by jonasmare** [comment]
@blawar 

It is not listing some DLC properly.
Ex: the new Eastward 'Octopia' DLC or the new updates for existing Vampire Survivors DLCs.

**Comment by blawar** [comment]
> @blawar
> 
> It is not listing some DLC properly. Ex: the new Eastward 'Octopia' DLC or the new updates for existing Vampire Survivors DLCs.

undiscovered DLC that is released after the initial title release is a different issue. I will do a scan for those now.

**Comment by blawar** [comment]
> @blawar
> 
> It is not listing some DLC properly. Ex: the new Eastward 'Octopia' DLC or the new updates for existing Vampire Survivors DLCs.

check to see if there is any missing DLC now: https://github.com/blawar/titledb/commit/4dc0094c8867eb298a235d9aee060b9136dfa256

**Comment by jonasmare** [comment]
From what i can tell it's now listing the aforementioned DLCs.

Though many have missing information ( are 'Untitled' ) like this tinfoil.io/Title/010071B00F63B001 or this tinfoil.io/Title/0100ACF013E9B001

**Comment by blawar** [comment]
> From what i can tell it's now listing the aforementioned DLCs.
> 
> Though many have missing information ( are 'Untitled' ) like this tinfoil.io/Title/010071B00F63B001 or this tinfoil.io/Title/0100ACF013E9B001

Your specific issue is still updating (yours is different than this issue), It will probably be complete within 24 hours.

**Comment by masagrator** [comment]
> the git repo should be up to date and accuarate now @jonasmare @masagrator
> 
> please re-open if you find any discrepencies.
> 
> [e973ed0](https://github.com/blawar/titledb/commit/e973ed0f162399dfa587a43b3a253e8afe05a09e)

Issue with Pokemons is gone, but ` We Love Katamari REROLL+ Royal Reverie` (010089D018D18000) still shows up as v2 while there is v3 available.

**Comment by masagrator** [comment]
Ah, nvm. I mistook japanese titleid with west titleid...
