### ISSUE TITLE
{region}.{language}.json update

### ISSUE THREAD

**Issue by FlameBeam** [blawar/titledb#4]
Hi! Will you update {region}.{language}.json in the future? These files are really helpful! 

If you won't update these json, how can I get these title database by myself? Thank you!!! 

I just need the icon image and screenshot url in the database. I can get JPN titles on the webpage, but cannot find the urls in USA/EUR/HK/KOR/CHN region.

**Comment by blawar** [comment]
They will be updated soon, there were some CDN changes / upgrades made which broke stuff.

**Comment by blawar** [comment]
https://github.com/blawar/titledb/commit/ef4d1a22a8eb9a29721e6836da68dca298581041
