### ISSUE TITLE
Where does the titleid comes from?

### ISSUE THREAD

**Issue by meduzen** [blawar/titledb#5]
Hi,

I see a lot of databases here and there having a `titleid` (e.g. `01007EF00011E000` for Breath of the Wild) but can’t find any official Nintendo endpoints delivering it.

Is it computed from another ID (the `nsu_id`?), and how? Or does it works differently (e.g. automated or manual contributions by the community)?

Thanks!

**Comment by throwawayay** [comment]
https://switchbrew.org/wiki/Network may be of interest, as may be https://www.reddit.com/r/SwitchHacks/comments/759myu/the_eshop_and_cdn_explained_switch_edition/

I would suggest just parsing and using the appropriate `{region}.{language}.json` for your nsuid <-> titleid mapping needs, the Nintendo endpoints are locked behind authentication
